events {
    worker_connections 1024;
}

http {
    include mime.types;
    sendfile on;

    server {
        listen 8000;
        listen [::]:8000;

        resolver 127.0.0.11;
        autoindex off;

        server_name _;
        server_tokens off;

        root /app/mbs/;
        index index.html;

        location /mbs {
            try_files $uri $uri/ /index.html;
        }

        location ~ .(static)/(js|css|media)/(.+)$ {
            try_files $uri $uri/ /$1/$2/$3;
        }        

        gzip_static on;
    }
}