name: aapp-mbs

# Default values
image:
  registry: saks01weuacrpgpgo5qvmwo.azurecr.io
  repository: aapp/images/mbs
  tag: 1.0.0

labels:
  app: aapp-mbs

serviceAccount: default
serviceAccounts:
  default:
      enableWorkloadIdentity: true

network:
  allow-ingress:
    selector: app == 'aapp-mbs'
    ingress:
      - action: Allow
    egress:
      - action: Allow

deployments:
  api:
    selectorLabels:
      component: api
    securityContext:
      runAsUser: 2000
    env:
      WEB_USERNAME: redactie@amsterdam.nl        
    autoscale:
      cpu: 70
      memory: 90
      min: 1
      max: 3        
    resources:
      requests:
        cpu: 200m
        memory: "200Mi"
      limits:
        cpu: 200m
        memory: "200Mi"
    volumes:
      - name: cache
        spec:
          emptyDir: {}
      - name: run
        spec:
          emptyDir: {} 
      - name: log
        spec:
          emptyDir: {}         
    containers:
      - name: main
        ports:
          - port: 8000
            name: http
        volumes:
          - name: cache
            mountPath: /var/cache/nginx
          - name: run
            mountPath: /var/run
          - name: log
            mountPath: /var/log/nginx
        secrets:
          - database
          - vault

secrets:
  certificate:
    type: keyvault
    tls: aapp-cert
      
services:
  api:
    selector:
      component: api
    ports:
      - port: 8000
        targetPort: 8000

ingress:
  mbs-external:
    className: nginx-external
    annotations:
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/rewrite-target: /mbs/$2
    paths:
      - path: /mbs(/?)(.*)
        pathType: ImplementationSpecific
        service: api
        port: 8000
