trigger: none

pr:
  - main

resources:
  repositories:
    - repository: templates
      type: git
      name: TAMM/templates
      ref: refs/tags/1.7.1

parameters:
  - name: registry
    type: string
    default: saks01weuacrpgpgo5qvmwo.azurecr.io

  - name: repository
    type: string
    default: aapp/images

  - name: name
    type: string
    default: mbs


extends:
  template: pipelines/aks/template.yaml@templates
  parameters:
    name: ${{ parameters.name }}
    version: $(Build.SourceBranchName)

    build:
      pool:
        name: ContainerBuilder

      # Trigger AquaSec scan
      producedImages:
      - ${{ parameters.repository }}/${{ parameters.name }}

      # Override default postSteps
      postSteps:
      - script: |
          az acr repository show-tags --name ${{ parameters.registry }} --repository ${{ parameters.repository }}/${{ parameters.name }}
        displayName: Show ${{ parameters.name }} image versions in S-ACR