trigger: none

pr:
  - main

resources:
  repositories:
    - repository: templates
      type: git
      name: Amsterdam-App/aapp_infra_common-azure-pipelines
      ref: refs/tags/1.8.0

parameters:
  - name: registry
    type: string
    default: saks01weuacrpgpgo5qvmwo.azurecr.io

  - name: repository
    type: string
    default: aapp/images

  - name: name
    type: string
    default: mbs


extends:
  template: pipelines/aks/template.yaml@templates
  parameters:
    name: ${{ parameters.name }}

    build:
      pool:
        name: ContainerBuilder