trigger:
  batch: true
  branches:
    include:
      - main
  tags:
    include:
      - "*.*.*"

resources:
  repositories:
    - repository: templates
      type: git
      name: Amsterdam-App/aapp_infra_common-azure-pipelines
      ref: refs/tags/1.8.0


parameters:
  - name: registry
    type: string
    default: saks01weuacrpgpgo5qvmwo.azurecr.io

  - name: repository
    type: string
    default: aapp/images

  - name: name
    type: string
    default: mbs  

  - name: force
    type: boolean
    default: false    

  - name: uninstall
    type: boolean
    default: false

extends:
  template: pipelines/aks/template.yaml@templates
  parameters:
    name: ${{ parameters.name }}
    version: $(Build.SourceBranchName)

    build:
      pool:
        name: ContainerBuilder

      # Trigger AquaSec scan
      producedImages:
      - ${{ parameters.repository }}/${{ parameters.name }}   

      # Override default postSteps
      postSteps:
      - script: |
          az acr repository show-tags --name ${{ parameters.registry }} --repository ${{ parameters.repository }}/${{ parameters.name }}
        displayName: Show ${{ parameters.name }} image versions in S-ACR
        
    dev:
      pool: Amsterdam-App
      namespace: ns-ccc-aapp-ont-01-aapp-ontw
      kubernetesServiceConnection: SCN-K8S-ns-ccc-aapp-ont-01-aapp-ontw

      ${{ if eq(parameters['force'], 'true') }}:
        preSteps: 
        - script: |
            helm uninstall ${{ parameters.name }}
          displayName: Helm uninstall ${{ parameters.name }}  

      ${{ if eq(parameters['uninstall'], 'true') }}:
        steps: 
        - script: |
            helm uninstall ${{ parameters.name }}
          displayName: Helm uninstall ${{ parameters.name }}

    test:
      pool: Amsterdam-App
      namespace: ns-ccc-aapp-tst-01-aapp-test
      kubernetesServiceConnection: SCN-K8S-ns-ccc-aapp-tst-01-aapp-test

      ${{ if eq(parameters['force'], 'true') }}:
        preSteps: 
        - script: |
            helm uninstall ${{ parameters.name }}
          displayName: Helm uninstall ${{ parameters.name }}

      ${{ if eq(parameters['uninstall'], 'true') }}:
        steps: 
        - script: |
            helm uninstall ${{ parameters.name }}
          displayName: Helm uninstall ${{ parameters.name }}

    acc:
      pool: Amsterdam-App
      namespace: ns-ccc-aapp-acc-01-aapp-acc
      kubernetesServiceConnection: SCN-K8S-ns-ccc-aapp-acc-01-aapp-acc

      ${{ if eq(parameters['force'], 'true') }}:
        preSteps: 
        - script: |
            helm uninstall ${{ parameters.name }}
          displayName: Helm uninstall ${{ parameters.name }}

      ${{ if eq(parameters['uninstall'], 'true') }}:
        steps: 
        - script: |
            helm uninstall ${{ parameters.name }}
          displayName: Helm uninstall ${{ parameters.name }} 
          
    prod:
      pool: Amsterdam-App
      namespace: ns-ccc-aapp-prd-01-aapp-prd
      kubernetesServiceConnection: SCN-K8S-ns-ccc-aapp-prd-01-aapp-prd

      ${{ if eq(parameters['force'], 'true') }}:
        preSteps: 
        - script: |
            helm uninstall ${{ parameters.name }}
          displayName: Helm uninstall ${{ parameters.name }}                                 