trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
    - manifests

pr: none

resources:
  repositories:
    - repository: templates
      type: git
      name: Amsterdam-App/templates
      ref: refs/tags/1.7.0


parameters:
  - name: registry
    type: string
    default: saks01weuacrpgpgo5qvmwo.azurecr.io

  - name: repository
    type: string
    default: aapp/images

  - name: name
    type: string
    default: mbs  

  - name: version
    type: string
    default: 1.0.4

  - name: force
    type: boolean
    default: false    

extends:
  template: pipelines/aks/template.yaml@templates
  parameters:
    name: ${{ parameters.name }}
    version: ${{ parameters.version }}

    dev:
      pool: Amsterdam-App
      namespace: ns-ccc-aapp-ont-01-aapp-ontw
      kubernetesServiceConnection: SCN-K8S-ns-ccc-aapp-ont-01-aapp-ontw

      ${{ if eq(parameters['force'], 'true') }}:
        preSteps: 
        - script: |
            helm uninstall ${{ parameters.name }}
          displayName: Helm uninstall ${{ parameters.name }}  


    # test:
    #   pool: Amsterdam-App
    #   namespace: ns-ccc-aapp-tst-01-aapp-test
    #   kubernetesServiceConnection: SCN-K8S-ns-ccc-aapp-tst-01-aapp-test

    #   ${{ if eq(parameters['force'], 'true') }}:
    #     preSteps: 
    #     - script: |
    #         helm uninstall ${{ parameters.name }}
    #       displayName: Helm uninstall ${{ parameters.name }}             