tenantId: 72fca1b1-2c2e-4376-a445-294d80196804
keyVaultName: shared-o-njo5j7pxxiapu
# az ad sp list --filter "startswith(displayName,'aapp-modules-o')"
workloadIdentity: abfcbcbc-a0f9-4610-a797-ce5723135792

host: ontw.app.amsterdam.nl
nodepool: cccaappont01

secrets:
  vault:
    type: keyvault
    keyVaultName: aapp-o-bgr6li3kaefcc  
    secrets:
      - aes-secret
      - app-token
      - secret-key
      - applicationinsights-connection-string
      
  database:
    type: opaque
    secrets:
      postgres-user: aapp-modules-o
      postgres-db: modules
      postgres-host: aapp-o-bgr6li3kaefcc.postgres.database.azure.com

# deployments:
#   echo-server:
#     autoscale:
#       cpu: 70
#       memory: 90
#       min: 2
#       max: 4

# ingress:
#   echo-server-internal:
#     paths:
#       - path: /echo-server
#         pathType: Prefix
#         service: echo-server
#         port: 80
#     tls:
#       secretNameOverride: aapp