keyVaultName: shared-o-njo5j7pxxiapu
# az ad sp list --filter "startswith(displayName, 'aapp-modules-o')"
workloadIdentity: abfcbcbc-a0f9-4610-a797-ce5723135792

host: ontw.app.amsterdam.nl
nodepool: cccaappont01

secrets:
  vault:
    type: keyvault
    keyVaultName: aapp-o-bgr6li3kaefcc  
    secrets:
      - web-password
      - aes-secret
      - secret-key      
      
  database:
    type: opaque
    secrets:
      postgres-user: aapp-modules-o
      postgres-db: modules
      postgres-host: aapp-o-bgr6li3kaefcc.postgres.database.azure.com