tenantId: 72fca1b1-2c2e-4376-a445-294d80196804
keyVaultName: shared-t-gdqxxofz6d2sw

# az ad sp list --filter "startswith(displayName,'aapp-modules-t')" => appId
workloadIdentity: fdadcd32-4900-486d-a705-3bd6aa9d3fd3

host: test.app.amsterdam.nl
nodepool: cccaapptst01

secrets:
  vault:
    type: keyvault
    keyVaultName: aapp-t-gub34v7g4neoa
    secrets:
      - aes-secret
      - app-token
      - secret-key
      - applicationinsights-connection-string
      
  database:
    type: opaque
    secrets:
      postgres-user: aapp-modules-t
      postgres-db: modules
      postgres-host: aapp-t-gub34v7g4neoa.postgres.database.azure.com